<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
* Implements hook_help().
*/
function hello_user_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hello_user':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is an custom module that print message "Zdravo User!" on path
      "/pozdrav-korisniku" ') . '</p>';
      return $output;
    default:
  }
}
